version: "3"

name: betro

services:
  redis:
    image: redis:latest
    restart: always
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: betro
      POSTGRES_DB: betro
      POSTGRES_PASSWORD: betro
    volumes:
      - postgres:/var/lib/postgresql/data
