volumes:
  postgres:
    driver: local

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: betro
      POSTGRES_DB: betro
      POSTGRES_PASSWORD: betro
    volumes:
      - postgres:/var/lib/postgresql/data
