name: Node.js CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432


    strategy:
      matrix:
        node-version: [18.x]
  

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - run: npm ci
      - run: env VITE_API_HOST="/" npm run build
      - run: sh ./test/setup.sh
        working-directory: ./libraries/client
        env:
          POSTGRES_URI: postgres://postgres:postgres@localhost:5432/postgres
          REDIS_URI: redis://localhost:6379
      - run: sh ./test/startServer.sh
        working-directory: ./libraries/client
        env:
          POSTGRES_URI: postgres://postgres:postgres@localhost:5432/postgres
          REDIS_URI: redis://localhost:6379
      - run: npm run test
        env:
          POSTGRES_URI: postgres://postgres:postgres@localhost:5432/postgres
          REDIS_URI: redis://localhost:6379
      - uses: codecov/codecov-action@v3
        with:
          env_vars: NODE_VERSION
        env:
          NODE_VERSION: ${{ matrix.node-version }}
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
  
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - run: npm ci
      - run: env VITE_API_HOST="/" npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          cache-to: type=inline
