name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.node-version }}-node
      - run: npm ci
      - run: npm run lint
      - run: npm run tsc
      - name: Build
        if: startsWith(matrix.node-version, '16')
        run: env BASE_URL="https://betro.easycode.cloud" VITE_API_HOST="https://betro.easycode.cloud" npm run build
      - uses: actions/upload-artifact@v2
        if: startsWith(matrix.node-version, '16')
        with:
          name: Release
          path: build/
